function result = collect_images(part, number_of_images)
    result = arrayfun( ...
        @(x) imread(append("res/",num2str(part),"/",num2str(x),".jpg")), ...
        1:number_of_images, ...
        'UniformOutput', ...
        false ...
    );
end